apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
  labels:
    app: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        - name: MONGO_HOST
          value: fleetman-mongodb
        ports:
        - containerPort: 8080
