apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: admin
    port: 8161
    targetPort: 8161
    nodePort: 30010
  - name: broker
    port: 61616
    targetPort: 61616
    nodePort: 30011
  type: NodePort
